src/main/java/com/example/likelion13thminihackathon/subject/controller/SubjectController.java
src/main/java/com/example/likelion13thminihackathon/subject/service/SubjectService.java

[feat] 과목 수정 구현

---

build.gradle
src/main/java/com/example/likelion13thminihackathon/config/SecurityConfig.java
src/main/java/com/example/likelion13thminihackathon/planner/Category.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerController.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerDTO.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerEntity.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerRepository.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerService.java

feat: 계획 추가

---

src/main/java/com/example/likelion13thminihackathon/jwt/JwtUtil.java
src/main/java/com/example/likelion13thminihackathon/subject/controller/SubjectController.java
src/main/java/com/example/likelion13thminihackathon/subject/dto/SubjectRequestDto.java
src/main/java/com/example/likelion13thminihackathon/user/controller/UserController.java
src/main/java/com/example/likelion13thminihackathon/user/service/UserService.java

[feat] 코드 리팩토링

---

src/main/java/com/example/likelion13thminihackathon/subjectMemo/controller/SubjectMemoController.java
src/main/java/com/example/likelion13thminihackathon/subjectMemo/dto/SubjectMemoRequestDto.java
src/main/java/com/example/likelion13thminihackathon/subjectMemo/dto/SubjectMemoResponseDto.java
src/main/java/com/example/likelion13thminihackathon/subjectMemo/entity/SubjectMemo.java
src/main/java/com/example/likelion13thminihackathon/subjectMemo/repository/SubjectMemoRepository.java
src/main/java/com/example/likelion13thminihackathon/subjectMemo/service/SubjectMemoService.java

[feat] 과목 메모 등록 구현

---

src/main/java/com/example/likelion13thminihackathon/planner/PlannerController.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerDTO.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerService.java

feat: 플래너 수정

---

src/main/java/com/example/likelion13thminihackathon/planner/PlannerController.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerService.java

feat: 플래너 삭제

---

src/main/java/com/example/likelion13thminihackathon/planner/PlannerController.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerRepository.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerService.java

feat: 플래너 카테고리별 조회

---

src/main/java/com/example/likelion13thminihackathon/planner/PlannerDTO.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerService.java

feat: 플래너 학기 수정

---

src/main/java/com/example/likelion13thminihackathon/college/CollegeController.java
src/main/java/com/example/likelion13thminihackathon/college/CollegeDataInitializer.java
src/main/java/com/example/likelion13thminihackathon/college/CollegeEntity.java
src/main/java/com/example/likelion13thminihackathon/college/CollegeRepository.java
src/main/java/com/example/likelion13thminihackathon/college/CollegeService.java

feat: 단과대학 조회

---

src/main/java/com/example/likelion13thminihackathon/college/CollegeDataInitializer.java
src/main/java/com/example/likelion13thminihackathon/college/CollegeRepository.java
src/main/java/com/example/likelion13thminihackathon/department/DepartmentController.java
src/main/java/com/example/likelion13thminihackathon/department/DepartmentDTO.java
src/main/java/com/example/likelion13thminihackathon/department/DepartmentDataInitializer.java
src/main/java/com/example/likelion13thminihackathon/department/DepartmentEntity.java
src/main/java/com/example/likelion13thminihackathon/department/DepartmentRepository.java
src/main/java/com/example/likelion13thminihackathon/department/DepartmentService.java
src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementController.java
src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementDTO.java
src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementEntity.java
src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementInit.java
src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementRepository.java
src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementService.java

feat: 학과목록 조회

---

src/main/java/com/example/likelion13thminihackathon/LikeLion13thMiniHackathonApplication.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoController.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoDTO.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoEntity.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoRepository.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoService.java

feat: 할 일 메모 등록

---

src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoCategory.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoController.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoDTO.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoEntity.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoRepository.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoService.java

feat: 할 일 메모 조회

---

src/main/java/com/example/likelion13thminihackathon/subject/controller/SubjectController.java
src/main/java/com/example/likelion13thminihackathon/subject/dto/SubjectRequestDto.java
src/main/java/com/example/likelion13thminihackathon/subject/dto/SubjectResponseDto.java
src/main/java/com/example/likelion13thminihackathon/subject/entity/Subject.java
src/main/java/com/example/likelion13thminihackathon/subject/repository/SubjectRepository.java
src/main/java/com/example/likelion13thminihackathon/subject/service/SubjectService.java

[feat] 과목 등록 & 조회 기능 수정

---

src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoController.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoEntity.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoService.java

feat: 할 일 메모 수정

---

src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoController.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoService.java

feat: 할 일 메모 삭제

---

src/main/java/com/example/likelion13thminihackathon/subject/controller/SubjectController.java
src/main/java/com/example/likelion13thminihackathon/user/controller/UserController.java
src/main/java/com/example/likelion13thminihackathon/user/dto/UserProfileResponseDto.java

[feat] 홈 화면용 프로필 조회

---

src/main/java/com/example/likelion13thminihackathon/achievement/controller/AchievementController.java
src/main/java/com/example/likelion13thminihackathon/achievement/dto/AchievementRequestDto.java
src/main/java/com/example/likelion13thminihackathon/achievement/dto/AchievementResponseDto.java
src/main/java/com/example/likelion13thminihackathon/achievement/entity/Achievement.java
src/main/java/com/example/likelion13thminihackathon/achievement/repository/AchievementRepository.java
src/main/java/com/example/likelion13thminihackathon/achievement/service/AchievementService.java

[feat] 나의 성취도 그래프 구현

---

src/main/java/com/example/likelion13thminihackathon/planner/PlannerController.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerDTO.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerEntity.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerRepository.java
src/main/java/com/example/likelion13thminihackathon/planner/PlannerService.java
src/main/java/com/example/likelion13thminihackathon/planner/Semester.java

feat: 플래너 조회 수정

---

src/main/java/com/example/likelion13thminihackathon/subject/service/SubjectStatisticService.java

[feat] 학점 계산기 기능 수정

---

src/main/java/com/example/likelion13thminihackathon/config/SecurityConfig.java
src/main/java/com/example/likelion13thminihackathon/user/dto/UserRequestDto.java
src/main/java/com/example/likelion13thminihackathon/user/entity/User.java

[feat] 회원정보 수정 & SecurityConfig 수정

---

src/main/java/com/example/likelion13thminihackathon/graduation/GraduationRequirementInit.java
src/main/java/com/example/likelion13thminihackathon/graduationMemo/GraduationMemoRepository.java

feat: 졸업요건 데이터 수정

---

src/main/java/com/example/likelion13thminihackathon/planner/Semester.java

feat: 플래너 학기
